/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.actions.first.workflow;

public class Library {

    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
