name: checkout workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: khyojun/cs-study
          ref: khyojun
      - run: ls-al

