name: OUR Second Workflow
on:
  issues:
      types: [opened, edited]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Issue updated'

  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name : Print working directory
        run: pwd
      - name : List files
        run: ls -al